version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=Agustina06
      - DB_NAME=gimnasio
    networks:
      - app-network

  frontend:
    build: 
      context: ./prueba_cursor
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Agustina06
      MYSQL_DATABASE: gimnasio
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
